---
title: "will-v-denzel raw"
author: "Chris Sarno"
date: "12/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(stringr)
library(rvest)

grabFilmInfoFromFilmsPage = function(page)
	{
	# 50 elements
	# # title = id = rank = year = rating = minutes = genre = votes = metascore = desc = millions
	
	movies = page %>%
		html_nodes(".mode-detail");
		
	
		
	pagecount = length(movies);
	
	result = data.frame( 			matrix(ncol = 11,nrow = pagecount) );
	# a matrix-type form with lots of NA values ...
	
	colnames(result) = c("rank", "title", "ttid", "year", "rated", "minutes", "genre", "ratings", "metacritic", "votes", "millions"); 
				
	
	for(i in 1:pagecount)
		{
		movie = movies[i];
		
		rank = movie %>%
			html_node(".lister-item-index") %>%
			html_text() %>%
			as.numeric();
		result$rank[i] = rank;
			
		title = movie %>%
			html_node(".lister-item-header a") %>%
			html_text();
		result$title[i] = title;
			
		ttid = movie %>%
			html_node(".lister-item-header a") %>%
			html_attr("href");
			
			temp = strsplit(ttid,"/",fixed=T);
		ttid = temp[[1]][3];
		result$ttid[i] = ttid;
		
		year = movie %>%
			html_node(".lister-item-year") %>%
			html_text();
		year = cleanupYear(year);
		result$year[i] = year;
		
		rated = movie %>%
			html_node(".certificate") %>%
			html_text();
		result$rated[i] = rated;
			
		minutes = movie %>%
			html_node(".runtime") %>%
			html_text();
		minutes = cleanupMinutes(minutes);
		result$minutes[i] = minutes;		
		
		genre = movie %>%
			html_node(".genre") %>%
			html_text();
		genre = str_trim(genre);
		result$genre[i] = genre;
		
		ratings = movie %>%
			html_node("div .rating-list") %>%
			html_attr("title");
				temp = strsplit(ratings,"/",fixed=T);
				temp = gsub("Users rated this","",temp[[1]][1],fixed=T);	
				temp = str_trim(temp);
		ratings = as.numeric(temp);
		result$ratings[i] = ratings;
		
		metacritic = movie %>%
			html_node(".ratings-metascore span") %>%
			html_text();
		metacritic = as.numeric(str_trim(metacritic));
		result$metacritic[i] = metacritic;
		
		info = movie %>%
			html_nodes(".lister-item-content p span") %>%
			html_text();
			
		votes = as.numeric(gsub(",","",info[8],fixed=T));
		result$votes[i] = votes;
		
		millions = cleanupMillions(info[11]);
		result$millions[i] = millions;			
		}
		
	result;
}

cleanupMillions = function(millions)
	{
	millions = gsub('$','',millions, fixed=T);
	millions = gsub('M','',millions, fixed=T);
	
	millions = as.numeric(millions);
	millions;
	}
	
cleanupMinutes = function(minutes)
	{
	minutes = gsub('min','',minutes, fixed=T);
	
	minutes = as.numeric(minutes);
	minutes;
	}
	
cleanupYear = function(year)
	{
	year = gsub('(','',year, fixed=T);
	year = gsub(')','',year, fixed=T);
	year = gsub('I','',year, fixed=T);
	year = as.numeric(year);
	year;
	}

grabNameFromFilmsPage = function(page)
	{
	name = page %>%
		html_node(".header") %>%
		html_text();
		
		name = gsub("Most Rated Feature Films With","",name,fixed=T);
		name = str_trim(name);
	
	name;
	}

	
grabFilmCountFromFilmsPage = function(page)
	{
	totalcount = page %>%
		html_nodes(".desc") %>%
		html_text();
		
		temp = strsplit(totalcount,"of",fixed=T);
		temp2 = strsplit(temp[[1]][2],"titles", fixed=T);
		
		totalcount = str_trim(temp2[[1]][1]);
		totalcount = as.numeric(totalcount);
		
		temp2 = strsplit(temp[[1]][1],"to", fixed=T);
		
		pagecount = str_trim(temp2[[1]][2]);
		pagecount = as.numeric(pagecount);
		
	result = list();
	
	result$totalcount = totalcount;
	result$pagecount = pagecount;
	
	result;
}

grabFilmsForPerson = function(nmid)
	{
	url = paste("https://www.imdb.com/filmosearch/?explore=title_type&role=",nmid,"&ref_=filmo_ref_typ&sort=num_votes,desc&mode=detail&page=1&title_type=movie", sep="");
	
	page1 = read_html(url);
	result = list();
	## useful for other data purposes
	result$nmid = nmid;
	
	## name of person
	result$name = grabNameFromFilmsPage(page1);
	result$countfilms = grabFilmCountFromFilmsPage(page1);
	
	result$movies.50 = grabFilmInfoFromFilmsPage(page1);
	
	result;
}
   nmid = "nm0000226";
 	will = grabFilmsForPerson(nmid);
 	plot(will$movies.50[,c(1,6,7:10)]);
  	boxplot(will$movies.50$millions);
		widx =  which.max(will$movies.50$millions);
	will$movies.50[widx,];
		summary(will$movies.50$year);  # bad boys for life ... did data change?

   nmid = "nm0000243";
 	denzel = grabFilmsForPerson(nmid);
 	plot(denzel$movies.50[,c(1,6,7:10)]);
  	boxplot(denzel$movies.50$millions);
		didx =  which.max(denzel$movies.50$millions);
	denzel$movies.50[didx,];
		summary(denzel$movies.50$year);
	
	par(mfrow=c(1,2));
	plot(will$movies.50$year,will$movies.50$millions, main="Smith Box Office", xlab="Year",ylim=c(0,360), ylab="Millions", type="h" )
	plot(denzel$movies.50$year,denzel$movies.50$millions, main="Denzel Box Office", xlab="Year",ylim=c(0,360), ylab="Millions", type="h" )
	summary(will$movies.50$millions)
	summary(denzel$movies.50$millions)
```
```{r}
	
# In the dollars department, there is no contest. Will Smith's movies have higher lows,
# higher highs, a higher average, and higher quartiles. Unequivocally, Will Smith's movies
# are a bigger success at the box office than Denzel Washington's. 

	par(mfrow=c(1,2));
	boxplot(will$movies.50$ratings, main=will$name, ylim=c(0,10), ylab="Ratings" )
	boxplot(denzel$movies.50$ratings, main=denzel$name, ylim=c(0,10), ylab="Ratings")
	 summary(will$movies.50$ratings)
  summary(denzel$movies.50$ratings)
```
```{r}

# Viewer ratings tell a different story than box office earnings. While Denzel's highest
# rated movies are unable to crack a rating of 8/10 like Will Smith's highest rated movie,
# his average movie rating, quartile ratings, and lowest rating are all higher. On average,
# viewers enjoy Denzel Washington's movies more than Will Smith's.

	par(mfrow=c(1,2));
	boxplot(will$movies.50$metacritic, main=will$name, ylim=c(0,100), ylab="Metacritic" )
	boxplot(denzel$movies.50$metacritic, main=denzel$name, ylim=c(0,100), ylab="Metacritic")
	par(mfrow=c(1,1))
  summary(will$movies.50$metacritic)
  summary(denzel$movies.50$metacritic)
	
# In general, critics seem to agree with the viewers. Their average rating of Denzel
# Washington's movies are higher, as well as the minumum and maximum ratings. There is a
# large area underneith the average in Will Smith's boxplot, indicating that his worse
# movies greatly outnumber his good movies, and thus bring down his metacritic average.
```

```{r}

library(devtools);
library(humanVerseWSU);

path.github = "https://raw.githubusercontent.com/MonteShaffer/humanVerseWSU/master/";

include.me = paste0(path.github, "misc/functions-nlp.R");
source_url( include.me );
include.me = paste0(path.github, "misc/functions-nlp-str.R");
source_url( include.me );
include.me = paste0(path.github, "misc/functions-nlp-stack.R");
source_url( include.me );
include.me = paste0(path.github, "misc/functions-nlp-pos.R");
source_url( include.me );
include.me = paste0(path.github, "humanVerseWSU/R/functions-encryption.R");
source_url( include.me );
path.to.nascent = "C:/Users/Alexander Nevsky/Dropbox/WSU-419/Fall 2020/__student_access__/unit_02_confirmatory_data_analysis/nascent/";

folder.nlp = "nlp/";
path.to.nlp = paste0(path.to.nascent, folder.nlp);


###### UPDATES TO dataframe subset function ######
# inflation adjustments for NA ... and improvements on subsetting
include.me = paste0(path.github, "humanVerseWSU/R/functions-dataframe.R");
source_url( include.me );
include.me = paste0(path.github, "humanVerseWSU/R/functions-inflation.R");
source_url( include.me );
library(imdb);
imdb::loadDataIMDB();
names(imdb.data);
humanVerseWSU::loadInflationData();

# Will Smith Data
will.search = IMDB.searchPersonName("Will* Smith*");

will.search;
will.nmid = will.search$nmid[1];
will.nmid = "nm0000226";
will.movies = IMDB.getMoviesForPerson(will.nmid);
will.movies;
will.movies = standardizeDollarsInDataFrame(will.movies, 2000, "millions", "year", "millions2000");
will.movies = sortDataFrameByNumericColumns(will.movies, "millions2000", "DESC");
will.movies$rank.money = 1:nrow(will.movies);
will.rank = subsetDataFrame(imdb.data$all.movies.actors.characters, "nmid", "==", will.nmid);
will.rank;
will.n = nrow(will.movies);
will.ttids = will.movies$ttid;
length( intersect(will.ttids, imdb.data$movies$popular50$ttid) );
mean(will.rank$actor.rank)
```
```{r}
# Denzel Washington Data
denzel.search = IMDB.searchPersonName("Denzel* Washington*");

denzel.search;
denzel.nmid = denzel.search$nmid[1];
#denzel.nmid = "nm0000226";
denzel.movies = IMDB.getMoviesForPerson(denzel.nmid);
denzel.movies;
denzel.movies = standardizeDollarsInDataFrame(denzel.movies, 2000, "millions", "year", "millions2000");
denzel.movies = sortDataFrameByNumericColumns(denzel.movies, "millions2000", "DESC");
denzel.movies$rank.money = 1:nrow(denzel.movies);
denzel.rank = subsetDataFrame(imdb.data$all.movies.actors.characters, "nmid", "==", denzel.nmid);
denzel.rank;
denzel.n = nrow(denzel.movies);
denzel.ttids = denzel.movies$ttid;
length( intersect(denzel.ttids, imdb.data$movies$popular50$ttid) );
mean(denzel.rank$actor.rank)
```

